#!/bin/bash

prev=a

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )

		if [[ prev != "$cur" ]]
		then
			
			if [ ! \( $cur -eq "I watched Avengers: Endgame. Thanos d**s..." \) ]
			then
				echo "$cur"
				prev=$cur
			else
				echo "Spoiler Alert"
				prev=$cur
		
			fi

		fi
	fi
done
